title: Str4thus' Cyber Adventures
description: It's dangerous to go alone!

url: https://str4thus.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: str4thus
  twitter: str4thus
  email: info@strathmann-cybersecurity.com