title:              Str4thus' Cyber Adventures
email:              info@strathmann-cybersecurity.com
description:        It is dangerous to go alone!
author:             Str4thus
baseurl:            "/"
url:                "https://str4thus.github.io"

# Social Profiles
twitter_username:   Str4thus
github_username:    Str4thus
linkedin_username:  jesse-strathmann-b29654213

# Build settings
markdown:           kramdown
#highlighter:        rouge
#kramdown:
#    input: GFM
#    syntax_highlighter: rouge

paginate:           15
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site